added function to call MCOR externally and changed length_trials from days to hours
pnnl/MCOR pull request #2
Opened 2023-08-29 00:12 UTC by rachel-g-long

Also updated the issue number to the correct one

2023-09-05 22:27 UTC, SarahFNewman requested changes
Here are a few high-level comments beyond the inline ones:
- I'd recommend separate branches and PRs for each JIRA ticket
- Please don't commit changes to the sample solar data
- I'd recommend updating integration_test.py to use the new run_mcor function
- Two of the tests in parameter_test.py are now failing, I suspect you'll need to update these for the hour/day change
- I'm also getting two failed tests in test_asp.py

2023-09-05 22:27 UTC, SarahFNewman commented on alternative_solar_profiles.py
> +            lambda x: stats.mode(x).mode[0])  # lambda x: x.mode(x).mode[0])
Please remove commented out code.

2023-09-05 22:27 UTC, SarahFNewman commented on main_files/main.py
>      # Note: it is strongly recommended to comment out the following two lines
Rather than including this comment, we should add two new input parameters (booleans) that will determine if those two methods are called.

2023-09-05 22:27 UTC, SarahFNewman commented on main_files/main.py
I think we want to have this function return the optim object and then everything below this line will get moved to the __main__ function below.

2023-09-05 22:27 UTC, SarahFNewman commented on main_files/main.py
> +    # commented out the old version of code (lines 137-352)
Please remove the commented out section.

2023-09-06 19:09 UTC, rachel-g-long commented
Will push up different branches and will remove this branch when done

2023-09-19 00:18 UTC, SarahFNewman approved these changes
Looks great!

2023-09-20 19:38 UTC, merged